services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - client

  client:
    build: ./client
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
